### PR TITLE
Clone TNW website

### PR DESCRIPTION
**Pull request by kagaramag**
## Description
Design TNW, A tech-focused magazine that uses media queries to gracefully degrade their site as the window size is reduced.  This responsive page touches on CSS technologies such as flexbox, grid, and also float an positioning to align element correctly as the page is resized to a smaller size.

### CODE REVIEW

**Comment by kobiyoyo** [comment]
## Pull Request under review, by Adama Chubiyojo Desmond (TSE)

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team       
#### Great Job so far, but there are a few more things required. 
### General
 - [ ] The Pull Request should have a meaningful  short description ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

* [ ] Elements should be aligned with [float](https://css-tricks.com/all-about-floats/) and [flex](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) or [grid](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/responsive_design/align_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59540217/))

#### Navigation bar
###### Large Screen 
* [ ] The search icon isn't positioned well compared to the links to the left .



 ###### Medium Screen 
* [ ] The links in this display arent postioned well.


### Latest news section
Mobile Screen
- [x] The text & img are too close,give space.

### Latest Funding section
 ###### Medium Screen 
- [ ] it should display 3 articles per row
Your Version

Original Version

 ###### Small Screen 
- [x] Position the texts well.


Latest deals section
- [x] Align the **See all Deals** to the right.

## [OPTIONAL]
 ###### Large Screen 1024px & above 
 ###### Medium Screen 768px > 1024px
 ###### Small Screen 480px > 768px
### Make changes and submit another code review request.
*Happy coding*

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Really fantastic work @kagaramag & @aulbytj! :medal_military: 
You have done beautifully well! Please consider my comments below, make the necessary changes and request another review.

#### Tablet screen size (between 1024 and 768px)
Beautiful work implementing some of the changes @kobiyoyo requested. Please consider that the tablet screen size has some more issues that need fixing. I have attached some screenshots of the sections in question, take note of the navigation bar, overflowing content and heading/subheading positionings.
screenshot
screenshot

Please request another review after making these changes! I wish you all the best and see you at the top! :rocket: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Nice work on the improvements :ok_hand: 
Please note that the issue in the navigation bar persists. See a screenshot below
screenshot

Make the corrections and request another review :ok_hand: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Comment by kagaramag** [comment]
> # Nice work on the improvements 👌
> Please note that the issue in the navigation bar persists. See a screenshot below
> screenshot
> 
> Make the corrections and request another review 👌
> 
> ##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

I am double-checking why it persists, I will get back to you ASAP.
Thanks

**Comment by kagaramag** [comment]
@Oluwadamilareolusaki and TSEs, I don't know if the issue was because I forced the latest commit with `--amend`. Can you kindly double-check for us to see if everything is okay

**Review by nikasulo — APPROVED** [review]
# Really great work @kagaramag and @aulbytj :rocket: 
You may merge and keep going :ok_hand: See you at the top! :medal_military: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Pull request merged**
